#line 2 "sql-lex.yy.c"

#line 4 "sql-lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[427] =
    {   0,
        0,    0,   94,   92,   50,   51,   51,   84,   92,   78,
       92,   92,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   80,   81,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   50,
       51,    0,    0,    0,    0,    0,   78,    0,   77,   91,
       91,   91,   91,   21,   91,   91,   11,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   71,   91,   91,   91,
       91,   91,   12,   91,   70,   73,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,    7,   91,   91,   91,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   53,   91,   91,   91,   91,
       91,    0,   90,    0,    0,    0,    0,   82,   89,    0,
       64,   91,   72,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   35,
       91,   43,   91,   91,   38,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   79,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   75,   91,   91,   91,   91,   42,   54,   91,
       91,   91,   91,   91,    0,    0,    0,   83,    0,   91,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   39,
       28,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   17,   23,   91,   91,   91,   20,   24,   91,
       91,   91,   91,   91,   91,   56,   91,   91,   91,   91,
       52,   91,   91,   20,    0,    0,    0,    0,    0,    4,
       91,   91,   15,   91,   59,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   62,   91,   67,   91,   91,    6,
        5,   91,   91,   91,   91,   91,   91,   91,    9,    2,
       91,   91,   91,   61,   69,   63,   91,   91,   91,   91,

       57,   18,   65,   91,   91,   91,   91,   91,    0,    0,
        0,    0,   16,   91,   91,   29,   91,    1,   91,   91,
       48,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,    3,   91,   91,   91,   91,   41,   91,   74,   91,
       26,   91,   91,   91,   91,   91,    0,    0,    0,   85,
       31,   49,   91,   44,   40,   36,   91,   91,   25,   91,
       91,   32,   91,   91,   91,   91,   91,   91,   91,   91,
       55,   30,   91,   68,   76,   22,   88,    0,    0,   91,
       66,   91,   14,   13,   91,   91,   91,   91,    8,   91,
       91,   91,   91,   87,    0,   91,   10,   91,   91,   91,

       91,   33,   19,   60,   27,    0,   58,   91,   37,   91,
       34,    0,   91,   91,    0,   91,   91,    0,   91,   91,
        0,   91,   45,   86,   46,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    1,    6,    7,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    9,    1,   10,
        1,   11,    1,    1,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,    1,   39,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   21,   51,   52,   53,
       54,   55,   21,   56,   57,   58,   59,   60,   61,   62,
       63,   37,   64,    1,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    1,    1,    2,    1,    3,    4,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    6,    1
    } ;

static const flex_int16_t yy_base[433] =
    {   0,
        0,    0,  524,  525,  521,  518,  518,   61,   61,  512,
      510,  507,   53,   49,   58,   58,    0,  491,  487,   56,
      499,  498,   68,   47,   65,   53,  497,   75,   85,   70,
       73,   70,  525,  525,   82,   81,  458,  470,  461,  464,
       79,  451,  453,   67,   67,  450,  103,  464,   97,  502,
      525,  494,  111,  437,  498,  489,  491,  448,  525,    0,
      482,  465,  480,    0,  109,  107,    0,  125,  478,  118,
      112,  453,  128,  463,  475,  135,    0,  111,  454,  477,
      127,  463,  456,  463,  462,    0,  459,  463,  425,  464,
      141,  146,  468,  134,  138,  140,    0,  132,  459,  458,

      461,  137,  145,  420,  434,  127,  415,  422,  419,  430,
      416,  408,  406,  406,  420,    0,  420,  405,  407,  406,
      141,  452,  451,    0,  174,  454,  455,  525,  525,  400,
        0,  440,    0,  155,  159,  436,  440,  439,  420,  421,
      171,  436,  437,  432,  431,  434,  416,  428,  168,    0,
      413,    0,  409,  408,    0,  417,  403,  422,  413,  378,
      419,  411,  417,  403,  399,    0,  401,  163,  417,  157,
      171,  400,  402,  397,  170,  174,  380,  368,  364,  364,
      379,  363,    0,  364,  365,  372,  358,    0,    0,  372,
      369,  350,  359,  172,  353,  401,  404,  525,  354,  378,

      171,  181,  390,  393,  382,  379,  371,  170,  375,  368,
      368,  378,  366,  380,  360,  184,  363,  381,  380,    0,
        0,  156,  379,  343,  360,  376,  363,  372,  369,  353,
      187,  358,    0,  176,  350,  363,  364,    0,    0,  334,
      337,  325,  331,  324,  329,    0,  331,  316,  311,  321,
        0,  320,  319,  313,  321,  307,  355,  358,  309,    0,
      176,  196,    0,  346,    0,  335,  330,  193,  333,  334,
      340,  337,  338,  329,    0,  195,    0,  329,  328,    0,
        0,  321,  293,  332,  307,  334,  326,  319,    0,    0,
      312,  186,  326,    0,    0,    0,  298,  287,  286,  293,

        0,    0,    0,  296,  279,  282,  281,  274,  270,  286,
      321,  287,    0,  196,  312,    0,  315,    0,  293,  294,
        0,  299,  293,  306,  194,  289,  288,  283,  273,  292,
      301,    0,  275,  300,  273,  210,    0,  254,    0,  253,
        0,  259,  260,  261,  260,  248,  247,  242,  247,  525,
        0,    0,  282,    0,    0,    0,  270,  275,    0,  283,
      282,    0,  240,  282,  283,  272,  277,  272,  201,  246,
        0,    0,  236,    0,    0,    0,  525,  231,  243,  262,
        0,  255,    0,    0,  254,  268,  252,  266,    0,  266,
      200,  224,  226,  525,  231,  246,    0,  220,  228,  245,

      218,    0,    0,    0,    0,  209,    0,  218,    0,  216,
        0,  195,  202,  207,  201,  200,  212,  179,  184,  214,
      172,  164,    0,  525,    0,  525,  254,  257,  261,  266,
      160,  271
    } ;

static const flex_int16_t yy_def[433] =
    {   0,
      426,    1,  426,  426,  426,  426,  426,  427,  426,  426,
      426,  426,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  426,  426,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  426,
      426,  426,  429,  426,  430,  426,  426,  426,  426,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,

      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  426,  426,  431,  429,  426,  430,  426,  426,  426,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  426,  426,  432,  426,  426,  428,

      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  426,  426,  426,  432,  426,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,

      428,  428,  428,  428,  428,  428,  428,  428,  426,  426,
      426,  426,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  426,  426,  426,  426,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  426,  426,  426,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  426,  426,  428,  428,  428,  428,  428,

      428,  428,  428,  428,  428,  426,  428,  428,  428,  428,
      428,  426,  428,  428,  426,  428,  428,  426,  428,  428,
      426,  428,  428,  426,  428,    0,  426,  426,  426,  426,
      426,  426
    } ;

static const flex_int16_t yy_nxt[591] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,   12,
        4,   13,   14,   15,   16,   17,   18,   19,   17,   20,
       17,   21,   22,   23,   24,   25,   26,   17,   27,   28,
       29,   30,   17,   31,   17,   17,   32,   33,   34,   17,
       17,   35,   36,   37,   17,   38,   39,   40,   41,   42,
       43,   17,   44,   45,   46,   17,   17,   47,   17,   48,
       49,   17,   17,    4,    4,   52,   55,   61,   65,   68,
       72,   56,   83,   73,   66,   62,   69,   63,   84,   81,
       76,   88,   64,   70,   67,   77,   71,   82,   91,   85,
       92,  101,  102,   86,   99,  103,   94,   65,   87,  100,

       95,   65,   66,   78,   96,   93,   89,   66,   78,   71,
       97,  113,  115,   71,   94,  123,  102,  124,   98,  116,
      114,  102,   96,  103,   54,   94,  134,  141,  105,   98,
       65,   78,  135,   96,  106,   66,   71,  120,  136,  104,
      139,  149,  140,   94,  143,  121,  168,   98,  147,  148,
      144,   96,  162,  152,  137,  134,  141,  164,  118,  163,
      135,  153,  169,  171,  197,  149,  170,  175,  149,  176,
      280,  175,  170,  165,  201,  168,  166,  179,  123,  180,
      124,  202,  208,  216,  281,  231,  234,  233,  238,  239,
      238,  171,  149,  170,  175,  261,  262,  176,  194,  170,

      268,  276,  290,  201,  425,  292,  313,  314,  318,  202,
      325,  208,  216,  231,  233,  234,  336,  238,  239,  254,
      351,  369,  359,  261,  391,  262,  403,  268,  424,  423,
      276,  290,  292,  313,  422,  421,  314,  318,  420,  325,
      419,  418,  417,  336,  416,  415,  414,  413,  351,  359,
      369,  412,  391,  411,  403,   53,  410,  409,   53,   53,
       60,   60,  125,  125,  125,  125,  127,  127,  127,  127,
      127,  127,  258,  408,  258,  258,  407,  406,  405,  404,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  390,  389,  388,  387,  386,  385,  384,  383,  382,

      381,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  358,  357,  356,  355,  354,  353,  352,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  324,  323,  322,  321,  320,  319,  317,  316,
      315,  312,  257,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  291,  289,  288,  287,  286,  285,  284,  283,
      282,  279,  278,  277,  275,  274,  273,  272,  271,  270,

      269,  267,  266,  265,  264,  263,  260,  259,  257,  256,
      255,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  237,  236,  235,  232,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  215,  214,  213,  212,  211,  210,  209,
      207,  206,  205,  204,  203,  200,  199,  128,  198,  196,
      195,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  178,  177,  174,  173,  172,  167,
      161,  160,  159,  158,  157,  156,  155,  154,  151,  150,
      146,  145,  142,  138,  133,  132,  131,  130,   57,  129,

      128,  126,  122,   50,  119,  117,  112,  111,  110,  109,
      108,  107,   90,   80,   79,   75,   74,   59,   58,   57,
       51,   51,   50,  426,    3,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426
    } ;

static const flex_int16_t yy_chk[591] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    9,   13,   14,   15,
       16,    9,   24,   16,   14,   13,   15,   13,   24,   23,
       20,   26,   13,   15,   14,   20,   15,   23,   28,   25,
       28,   31,   31,   25,   30,   32,   29,   14,   25,   30,

       29,   35,   14,   41,   29,   28,   26,   35,   20,   36,
       29,   44,   45,   15,   47,   53,   49,   53,   47,   45,
       44,   31,   47,   32,    8,   29,   65,   71,   36,   29,
       35,   41,   66,   29,   36,   35,   36,   49,   68,   35,
       70,   78,   70,   47,   73,   49,   94,   47,   76,   76,
       73,   47,   91,   81,   68,   65,   71,   92,   47,   91,
       66,   81,   95,   96,  431,   76,   98,  102,   78,  103,
      222,  121,   95,   92,  134,   94,   92,  106,  125,  106,
      125,  135,  141,  149,  222,  168,  171,  170,  175,  176,
      194,   96,   76,   98,  102,  201,  202,  103,  121,   95,

      208,  216,  231,  134,  422,  234,  261,  262,  268,  135,
      276,  141,  149,  168,  170,  171,  292,  175,  176,  194,
      314,  336,  325,  201,  369,  202,  391,  208,  421,  420,
      216,  231,  234,  261,  419,  418,  262,  268,  417,  276,
      416,  415,  414,  292,  413,  412,  410,  408,  314,  325,
      336,  406,  369,  401,  391,  427,  400,  399,  427,  427,
      428,  428,  429,  429,  429,  429,  430,  430,  430,  430,
      430,  430,  432,  398,  432,  432,  396,  395,  393,  392,
      390,  388,  387,  386,  385,  382,  380,  379,  378,  373,
      370,  368,  367,  366,  365,  364,  363,  361,  360,  358,

      357,  353,  349,  348,  347,  346,  345,  344,  343,  342,
      340,  338,  335,  334,  333,  331,  330,  329,  328,  327,
      326,  324,  323,  322,  320,  319,  317,  315,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  300,  299,  298,
      297,  293,  291,  288,  287,  286,  285,  284,  283,  282,
      279,  278,  274,  273,  272,  271,  270,  269,  267,  266,
      264,  259,  258,  257,  256,  255,  254,  253,  252,  250,
      249,  248,  247,  245,  244,  243,  242,  241,  240,  237,
      236,  235,  232,  230,  229,  228,  227,  226,  225,  224,
      223,  219,  218,  217,  215,  214,  213,  212,  211,  210,

      209,  207,  206,  205,  204,  203,  200,  199,  197,  196,
      195,  193,  192,  191,  190,  187,  186,  185,  184,  182,
      181,  180,  179,  178,  177,  174,  173,  172,  169,  167,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      154,  153,  151,  148,  147,  146,  145,  144,  143,  142,
      140,  139,  138,  137,  136,  132,  130,  127,  126,  123,
      122,  120,  119,  118,  117,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  105,  104,  101,  100,   99,   93,
       90,   89,   88,   87,   85,   84,   83,   82,   80,   79,
       75,   74,   72,   69,   63,   62,   61,   58,   57,   56,

       55,   54,   52,   50,   48,   46,   43,   42,   40,   39,
       38,   37,   27,   22,   21,   19,   18,   12,   11,   10,
        7,    6,    5,    3,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "sql-lex.l"
#line 2 "sql-lex.l"
#include "common_defs.h"
#include "sql.tab.h"
int n_lines = 1;
#line 725 "sql-lex.yy.c"
#line 726 "sql-lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 10 "sql-lex.l"


#line 946 "sql-lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 427 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 525 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 12 "sql-lex.l"
{
	return CREATE;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "sql-lex.l"
{
	return TABLE;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 20 "sql-lex.l"
{
	return SCHEMA;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "sql-lex.l"
{
	return ALTER;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 29 "sql-lex.l"
{
	return OWNER;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "sql-lex.l"
{
	return OWNED;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "sql-lex.l"
{
	return TO;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "sql-lex.l"
{
	return SEQUENCE;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "sql-lex.l"
{
	return START;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "sql-lex.l"
{
	return INCREMENT;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "sql-lex.l"
{
	return BY;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 57 "sql-lex.l"
{
	return NO;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "sql-lex.l"
{
	return MINVALUE;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "sql-lex.l"
{
	return MAXVALUE;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 70 "sql-lex.l"
{
	return CACHE;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 75 "sql-lex.l"
{
	return BIGINT;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "sql-lex.l"
{
	return TEXT;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 84 "sql-lex.l"
{
	return JSONB;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 88 "sql-lex.l"
{

	return TIMESTAMP;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 93 "sql-lex.l"
{
	return WITH;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 97 "sql-lex.l"
{
	return AS;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "sql-lex.l"
{
	return WITHOUT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 106 "sql-lex.l"
{
	return TIME;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "sql-lex.l"
{
	return ZONE;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 115 "sql-lex.l"
{
	return INTEGER;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 119 "sql-lex.l"
{
	return DOUBLE;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 123 "sql-lex.l"
{
	return PRECISION;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 127 "sql-lex.l"
{
	std::cout << "return ONLY " << std::endl;
	return ONLY;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 132 "sql-lex.l"
{
	return COLUMN;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 136 "sql-lex.l"
{
	return NEXTVAL;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 140 "sql-lex.l"
{
	return BOOLEAN;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 144 "sql-lex.l"
{
	return PRIMARY;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 148 "sql-lex.l"
{
	return TENANT_ID;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 152 "sql-lex.l"
{
	return SEARCH_KEY;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 157 "sql-lex.l"
{
	return KEY;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 161 "sql-lex.l"
{
	return FOREIGN;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 165 "sql-lex.l"
{
	return REFERENCES;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 169 "sql-lex.l"
{
	return NOT;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 173 "sql-lex.l"
{
	return NULLL;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 177 "sql-lex.l"
{
	std::cout << "returning DEFAULT: " << std::endl;
	return DEFAULT;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 182 "sql-lex.l"
{
	return UNIQUE;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 186 "sql-lex.l"
{
	return now;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 190 "sql-lex.l"
{
	return MAP;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 194 "sql-lex.l"
{
	return DB_CONV;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 198 "sql-lex.l"
{
	return SCALA_DATATYPE;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 202 "sql-lex.l"
{
	return PostgresToScala;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 206 "sql-lex.l"
{
	return FOREIGN;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 210 "sql-lex.l"
{
	return DELETE;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 214 "sql-lex.l"
{
	return CASCADE;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 219 "sql-lex.l"
{
	// discard whitespace
}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 223 "sql-lex.l"
{
	// discard newlines - we'll count them later
	++n_lines;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 228 "sql-lex.l"
{
	string s(yytext); 
	if (s == "true") {
		yylval.bboolean = true;
	} else {
		yylval.bboolean = false;
	}
	std::cout << "returning bboolean: " << yylval.bboolean << std::endl;
	return BBOOLEAN;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 239 "sql-lex.l"
{
	yylval.bboolean = true;
	return BBOOLEAN;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 244 "sql-lex.l"
{
	yylval.bboolean = false;
	return BBOOLEAN;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 249 "sql-lex.l"
{
	string * id = new string(yytext);
	yylval.text_val = id;
	return TEXT_VAL;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 255 "sql-lex.l"
{
	return HEAP;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 259 "sql-lex.l"
{
	string s(yytext); 
	if (s == "true") {
		yylval.bboolean = true;
	} else {
		yylval.bboolean = false;
	}
	std::cout << "returning bboolean: " << yylval.bboolean << std::endl;
	return BBOOLEAN;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 270 "sql-lex.l"
{
	return CONSTRAINT;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 274 "sql-lex.l"
{
	return CHECK;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 278 "sql-lex.l"
{
	return CHARACTER;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 282 "sql-lex.l"
{
	return USING;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 286 "sql-lex.l"
{
	return INDEX;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 290 "sql-lex.l"
{
	return BTREE;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 294 "sql-lex.l"
{
	return ADD;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 298 "sql-lex.l"
{
	return LOWER;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 302 "sql-lex.l"
{
	return GREATEST;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 306 "sql-lex.l"
{
	return LEAST;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 310 "sql-lex.l"
{
	return VARYING;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 315 "sql-lex.l"
{
	return WHERE;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 319 "sql-lex.l"
{
	return ON;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 323 "sql-lex.l"
{
	return IS;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 328 "sql-lex.l"
{
	return AND;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 332 "sql-lex.l"
{
	return OR;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 336 "sql-lex.l"
{
	return COLUMN;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 340 "sql-lex.l"
{
	return GIN;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 345 "sql-lex.l"
{
	return WARNING;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 349 "sql-lex.l"
{
	return NE;
}
	YY_BREAK
/*
	false {
		yylval.boolean = false;
		return boolean;
	}
	*/
case 78:
YY_RULE_SETUP
#line 360 "sql-lex.l"
{
	string num_str (yytext);
	yylval.number = atoi(num_str.c_str());
	return NUMBER;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 366 "sql-lex.l"
{
	return SET;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 370 "sql-lex.l"
{
	return LSQB;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 374 "sql-lex.l"
{
	return RSQB;
}
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 379 "sql-lex.l"
{
	// ignore comment, but track the line number
	++n_lines;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 384 "sql-lex.l"
{
	return EMPTY_JSON;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 388 "sql-lex.l"
{
	return QUOTE ;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 392 "sql-lex.l"
{
	return CAST_TO_JSONB;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 397 "sql-lex.l"
{
	string * id = new string(yytext);
	yylval.text_val = id;
	return CAST_TO_REG_CLASS;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 403 "sql-lex.l"
{
	string * id = new string(yytext);
	yylval.text_val = id;
	return TEXT_VAL;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 409 "sql-lex.l"
{
	string * id = new string(yytext);
	yylval.text_val = id;
	return TEXT_VAL;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 415 "sql-lex.l"
{
	return JSON_FIELD_EXTRACTOR;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 419 "sql-lex.l"
{
	string * id = new string(yytext);
	yylval.text_val = id;
	return TEXT_VAL;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 425 "sql-lex.l"
{
	string * id = new string(yytext);
	yylval.identifier = id;
	//std::cout << "return identifier: " << *id << std::endl;
	return identifier;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 432 "sql-lex.l"
{
	//std::cout << "return single char token: " << yytext[0] << std::endl;
	return yytext[0];
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 438 "sql-lex.l"
ECHO;
	YY_BREAK
#line 1697 "sql-lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 427 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 427 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 426);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 438 "sql-lex.l"



